url: https://aviralg.github.com/blog
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude: ["Makefile", "README.md", "Rakefile", "generate.rb", "writeup_image.rb", "Gemfile", "Gemfile.lock"]
include: ["_pages"]
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
author:
  name: Aviral Goel
  email: goel.aviral@gmail.com
  url: https://aviralg.github.com/blog
title: Aviral Goel's Blog
feed:
  path: atom.xml
